### ISSUE TITLE
GET_RECORD_FAIL - permission problem only in production app

### ISSUE THREAD

**Issue by Fudal** [duynguyen242/flutter_health_connect#13]
When I'm using:
```
    final result = await HealthConnectFactory.getRecord(
      type: type,
      startTime: DateTime(2000),
      endTime: DateTime.now(),
    );
```

I have error:
```
PlatformException(GET_RECORD_FAIL, com.package.name lacks the following permissions: [android.permission.health.READ_BLOOD_PRESSURE], java.lang.SecurityException: com.package.name lacks the following permissions: [android.permission.health.READ_BLOOD_PRESSURE]
	at androidx.health.platform.client.impl.error.ErrorStatusConverterKt.toException(ErrorStatusConverter.kt:47)
	at androidx.health.platform.client.impl.ReadDataRangeCallback.onError(ReadDataRangeCallback.kt:35)
	at androidx.health.platform.client.service.IReadDataRangeCallback$Stub.onTransact(IReadDataRangeCallback.java:75)
	at android.os.Binder.execTransactInternal(Binder.java:1331)
	at android.os.Binder.execTransact(Binder.java:1268)
, null)
```
but that error is only in production app.

Of course my app has permissions in androidManifest:
```

    <uses-permission android:name="android.permission.health.READ_HEART_RATE"/>
    <uses-permission android:name="android.permission.health.READ_BLOOD_PRESSURE"/>
```

**Comment by Fudal** [comment]
@duynguyen242 do you have any idea why that is happened?

**Comment by owjoh** [comment]
@Fudal did you ever figure out a fix for this?

**Comment by Fudal** [comment]
@owjoh yes, probably - you need to fill that form https://docs.google.com/forms/d/1LFjbq1MOCZySpP5eIVkoyzXTanpcGTYQH26lKcrQUJo/viewform?edit_requested=true&pli=1 to have the access to Health Connect API data.

**Comment by owjoh** [comment]
@Fudal thanks for the response. Where did you find this form? I can't seem to find any docs that reference it

**Comment by Fudal** [comment]
@owjoh I found that here: https://developer.android.com/guide/health-and-fitness/health-connect/get-started

**Comment by Fudal** [comment]
@owjoh Did it work for you?
