### ISSUE TITLE
Crash after permission grant  @FlutterHealthConnectPlugin.kt:95

### ISSUE THREAD

**Issue by softkot** [duynguyen242/flutter_health_connect#3]
```
E/AndroidRuntime( 3514): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 3514): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime( 3514): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
E/AndroidRuntime( 3514): 	at dev.duynp.flutter_health_connect.FlutterHealthConnectPlugin$onActivityResult$1.invokeSuspend(FlutterHealthConnectPlugin.kt:95)
E/AndroidRuntime( 3514): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime( 3514): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime( 3514): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 3514): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3514): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime( 3514): 	at android.app.ActivityThread.main(ActivityThread.java:8061)
E/AndroidRuntime( 3514): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3514): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime( 3514): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/AndroidRuntime( 3514): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@776c445, Dispatchers.Main]
```

**Comment by softkot** [comment]
Pull request a fix https://github.com/duynguyen242/flutter_health_connect/pull/4
